version: 2
jobs:
  build:
    docker:
      - image: curvetomorrow/auslan-dev-image:v7.8
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    working_directory: /var/www/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Heroku
          shell: /bin/bash -l
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./.circleci/setup-heroku.sh
            fi
      - run:
          name: Setup the environment
          shell: /bin/bash -l
          command: |
           apt-get update
           apt-get --only-upgrade install google-chrome-stable -y
           export CHROME_BIN=$(which google-chrome)
           bundle install
           service postgresql restart
           sleep 2
           bundle exec rake db:create
           bundle exec rake db:migrate
      - run:
          name: Run Rubocop
          shell: /bin/bash -l
          command: |
           bundle exec rubocop
      - run:
          name: Run RSpec
          shell: /bin/bash -l
          command: |
           bundle exec rspec
      - run:
          name: Run Cucumber
          shell: /bin/bash -l
          command: |
            bundle exec cucumber
      - store_test_results:
          path: /tmp/rspec
      - store_artifacts:
          path: ./coverage
      - deploy:
          name: Deploy Master to Heroku
          shell: /bin/bash -l
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              git push heroku master -f
              heroku run rake db:migrate
              heroku restart
            fi
