version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: Run RSpec
          shell: /bin/bash -l
          command: |
           bundle exec rspec