version: 2
jobs:
  build:
    docker:
      docker:
        - image: circleci/ruby:2.3.1-browsers
        - image: circleci/postgres:9.6.2-alpine
    working_directory: /var/www/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup the environment
          shell: /bin/bash -l
          command: |
           bundle install
           service postgresql restart
           sleep 2
           bundle exec rake db:create
           bundle exec rake db:migrate
      - run:
          name: Run Rubocop
          shell: /bin/bash -l
          command: |
           bundle exec rubocop
      - run:
          name: Run RSpec
          shell: /bin/bash -l
          command: |
           bundle exec rspec
      - run:
          name: Run Cucumber
          shell: /bin/bash -l
          command: |
            bundle exec cucumber
      - store_test_results:
          path: /tmp/rspec
      - store_artifacts:
          path: ./coverage