version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: Setup the environment
          shell: /bin/bash -l
          command: |
           bundle install
      - run:
          name: Run RSpec
          shell: /bin/bash -l
          command: |
           bundle exec rspec
      - store_test_results:
          path: /tmp/rspec
      - store_artifacts:
          path: ./coverage