QUS = {
    step_two_questions:
        [{question_id: 1, qus: 'I understand I have provided a sample so that my DNA can be extracted and all of my genes could be looked at. This is called a genomic test.', description: 'The sample you have given may have been blood, saliva, hair follicle, skin or other sample already collected as part of your medical care. All of these samples contain your cells, and your DNA can be extracted from the cells in the sample. Your DNA is needed for the genomic test. DNA makes up genes. Genes are inside almost every cell of your body. There are over 20,000 genes in each of your cells, and together these genes make up your “genome”. Each gene has a specific function, however the function of all genes is not yet known. Variations in genetic information in different people can occur, which is why we are all unique. Most variations are harmless, but other variations can make a gene not work, resulting in a disorder or health condition. Identifying variations may help to find the cause of your health condition. Previously, testing to look for variations in genes involved looking at only one gene at a time. There are now new ways where tests can look at many or all of our genes at once. This is known as “genomic testing.'},
         {question_id: 2, qus: 'I understand having a genomic test may not find the genetic cause of my condition.', description: 'The likelihood of finding a genetic cause depends on a number of things, including your health condition and how much is already known about it. We are still learning about what genes do and how they work. Between 30 and 60% of rare disease patients receive a diagnosis through genomic testing. That is, 3 to 6 people in every 10 tested will receive a genetic explanation for their condition. We expect more patients will receive a diagnosis in the future, as the technology and our ability to interpret genomic information improve.'},
         {question_id: 3, qus: 'I understand my sample and genomic information will be stored by the testing laboratory so that it could be looked at again in the future, when we know more about genes that cause my health condition.', description: 'How long the laboratory stores the sample is defined by its own standard practices and relevant legal requirements. You should expect the sample may be kept for at least three months, but perhaps years. The testing laboratory will keep the genomic information they get from your sample so that if there is a specific reason or request to do so, they can look at your genomic information again (do a re-analysis). An example of when this might be done is if new gene variants linked with your health condition are identified.'},
         {question_id: 4, qus: 'I understand that my genomic testing results will be considered confidential but shared with the medical team involved in my care.', description: 'This may include your Clinical Geneticist and other specialist doctors, Genetic Counsellor and GP.'},
         {question_id: 5, qus: 'I understand that the testing laboratory may share my anonymised genomic information with other laboratories, in order to understand more about the genetic changes that can cause my health condition or other conditions.', description: 'Sharing your genomic information could be with clinical or research laboratories. All of your personal information is removed before it is shared, so there is very little chance it could be linked back to you. Your information is anonymised in this case, meaning the record that it is your sample is not kept. This means that you will probably not personally benefit from anything that sharing your information finds.'},
         {question_id: 6, qus: 'I understand the laboratory performing my test will store and may sometimes use my DNA sample for purposes like reference and control material.', description: 'Your DNA is stored in the testing laboratory, for at least three months, but perhaps years. When doing any laboratory test, it is important to compare the test sample with a control sample. Your DNA may end up being used as the control sample. All of your personal, identifying information will be removed from it, if it is used for this purpose.'},
         {question_id: 7, qus: 'I understand there are certain risks involved in having a genomic test. These may include finding out something that may be important for my family’s health, incidental findings, or having to disclose the genomic information.', description: 'The main risks involved in having a genomic test are related to the information that you may get, rather than any physical harm. Waiting for the test results, or the results you receive, may bring up a number of different emotions. We may be uncertain about the significance of your result. It may be uncomfortable or cause stress to share a result with your family. The test may find something important to your health that you or the doctors were not expecting (an inicidental finding). You may have to disclosure the information to insurance companies or employers (there is more information on this below).'},
         {question_id: 8, qus: 'I understand that it might be important to tell my family members about genetic changes that could directly affect their health. Every attempt will be made for them to receive that information from me, supported by my medical team.', description: 'Family members who may have an interest in knowing about your result are your biological, or blood relatives. These people could include your parents, children, aunties and uncles and cousins. If you are planning to have (more) children with your partner, they may need to know. Exactly who needs to know is different on a case by case basis. Your medical team will help you by telling you who will need to know.'},
         {question_id: 9, qus: 'I understand that if I am taking out a new policy for life, critical illness or income protection insurance, the insurer may ask me to disclose that I have had a genetic test and require me to provide my results.', description: 'In Australia, how having had genetic or genomic testing affects your ability to gain certain types of insurance is currently being debated by government. If you would like more information about the impact of genetic testing on certain insurance products, visit the Centre for Genetics Education insurance fact sheet.'},
         {question_id: 10, qus: 'I understand my employer, or future employers, may ask for my results to decide whether there is a risk associated with a particular job role.', description: "It is lawful for an employer to ask for your genetic testing results, if they think it is relevant in deciding whether you are able to fulfil a job role. In reality, very few employers do ask for your genetic testing results at this time, but it's important that you know it may become more relevant in the future."},
         {question_id: 11, qus: 'I understand all of the information and statements well enough to answer them.', description: ''},
        ],

    step_three_questions:
        [{question_id: 12, qus: 'I understand that the researchers will collect information from my health records.', description: 'We will ask the Commonwealth Government Department of Health for your Medical Benefit Scheme (MBS) and Pharmaceutical Benefits Scheme (PBS) information, covering a period of up to 8 years. We will ask Data Linkage agencies in each State or Territory of Australia for your hospital inpatient records and emergency visit records. This information will cover a period of up to 14 years. This information will be very important for us to understand how having a genomic test and a genomic diagnosis might reduce the long-term costs of health care for the government. Access to the information is tightly regulated to protect your privacy, and we only receive it after applying for it through the proper channels. We will also be required to destroy it after we finished using it.'},
         {question_id: 13, qus: 'I understand that at times during the research project I will be asked to complete surveys or questionnaires. I’ll be reminded when they are ready to complete and know that I can ask for help to do them.', description: 'The surveys and questionnaires will be very important for us to understand aspects like your views of genomic testing, your understanding of genomic testing, your personal experiences of the test and the financial cost to you of having the test. Sometimes, we also ask you questions about the financial costs of having a health condition.'},
         {question_id: 14, qus: 'I understand all of the information and statements well enough to answer them.', description: ''},
        ],

    step_four_questions:
        [{question_id: 15, qus: 'I want to know about the genetic change if it is medically actionable (will alter my health management or treatment).', description: 'For example, there are some types of cancers that run in families. Sometimes we can find a genetic change that means a family is more likely to develop a cancer throughout their lifetime. If this genetic change is medically actionable, it means these families can reduce that risk through closer surveillance or surgical options.'},
         {question_id: 16, qus: 'I want to know about the genetic change even if it is non-medically actionable (will not alter my health management or treatment)', description: 'There are some conditions that we know can run in families and we know the genetic cause of, but cannot be treated. An example of this is early onset Alzheimer’s disease. This type of result would mean that you would know that you are at risk of developing this condition, but at this time your health management or treatment would not change.'},
         {question_id: 17, qus: 'I want to know if I am a carrier of a genetic change that can cause disease (it might affect decisions I make about having children, or for my grandchildren)', description: 'Sometimes we can be “carriers” of genetic changes that do not affect our health but can cause problems when we have a baby with a partner who also carries that same genetic change. An example of this is cystic fibrosis.'},
         {question_id: 18, qus: 'For any changes that don’t fit in the above categories, my medical team and the testing laboratory can decide whether I should be told about the findings on a case by case basis', description: ''},
         {question_id: 19, qus: 'I would like a summary of the main findings of my genomic testing report stored here, so I can access it at any time', description: 'We are developing ways of showing your genomic results in a way that is understandable to you, your family and anyone else you would like to show them to. We will make this available to you as soon as it is ready, if you indicate that you would like to have it.'},
         {question_id: 20, qus: 'I understand all of the information and statements well enough to answer them.', description: ''},
        ],

    step_five_questions:
        [{question_id: 21, qus: 'Not-for-profit research organisations (eg Murdoch Children’s Research Institute)', description: ''},
         {question_id: 22, qus: 'Universities and research institutes (eg The University of Melbourne)', description: ''},
         {question_id: 23, qus: 'Government (eg Australian Government Department of Health)', description: ''},
         {question_id: 24, qus: 'Commercial companies (eg pharmaceutical companies)', description: ''},
         {question_id: 25, qus: 'General research use and clinical care', description: 'General research use and clinical care refers to research where, for example, your genomic information might shared through clinical networks internationally to see if there are any other cases in the world like yours. This is for clinical benefit, but because of the close links between clinical and research genomics, your genomic and other health information will likely also end up in a research setting.'},
         {question_id: 26, qus: 'Health/medical/biomedical research', description: 'Health, medical and biomedical research could include research into understanding how a genetic change affects the functioning of a tissue or organ or whole-body system and is done in a research laboratory setting.'},
         {question_id: 27, qus: 'Research specific to my condition', description: 'Your genomic information may be helpful to study other health conditions, but if you prefer, we can restrict sharing your genomic information to research into your condition.'},
         {question_id: 28, qus: 'Population and ancestry research', description: 'Population and ancestry research may include working out how or when a certain genetic change arose in a population, studying traits of certain populations, or your information may be aggregated with many other people’s information to be part of a control or reference dataset. This helps to determine normal variation in populations.'},
         {question_id: 29, qus: 'I agree to my health information being shared with other research studies that don’t need my genomic information (eg just my MRIs, blood test or other results)', description: ''},
         {question_id: 30, qus: 'In the above sections I have agreed to my samples and genomic / health information being used in some way for other research projects, both now and in the future. I would prefer to be contacted every time my de-identified samples or information is shared', description: ''},
         {question_id: 31, qus: 'I understand all of the information and statements well enough to answer them.', description: ''},
        ]

}