default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'agha_development' %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

test: &test
  <<: *default
  database: agha_test
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD']  %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

production:
  <<: *default
  database: agha_production
  username: <%= ENV['RDS_USERNAME'] || 'agha' %>
  password: <%= ENV['RDS_PASSWORD'] || 'agha' %>

cucumber:
  <<: *test
