on: [push]
jobs:
  run-rspec:
    name: "rspec"
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker-compose build
      - env:
          MASTER_KEY: ${{ secrets.MASTER_KEY }}
        run: printf "${MASTER_KEY}" > config/master.key
      - run: docker-compose --env-file=.env.test run web yarn install
      - run: docker-compose --env-file=.env.test run web bundle exec rails db:create
      - run: docker-compose --env-file=.env.test run web bundle exec rails db:migrate
      - run: docker-compose --env-file=.env.test run web bundle exec rails db:seed
      - run: docker-compose --env-file=.env.test run web bundle exec rspec
  run-cucumber:
    name: "cucumber"
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker-compose build
      - env:
          MASTER_KEY: ${{ secrets.MASTER_KEY }}
        run: printf "${MASTER_KEY}" > config/master.key
      - run: docker-compose --env-file=.env.test run web yarn install
      - run: docker-compose --env-file=.env.test run web bundle exec rails db:create
      - run: docker-compose --env-file=.env.test run web bundle exec rails db:migrate
      - run: docker-compose --env-file=.env.test run web bundle exec rails db:seed
      - run: |
          docker-compose --env-file=.env.test up -d
          # Wait until the selenium container is ready
          while ! curl -s http://localhost:4444/wd/hub/status | grep -qF '"ready": true'
          do
            echo selenium not ready, retrying in 5 seconds...
            sleep 5
          done
          docker-compose --env-file=.env.test run web bundle exec rake cucumber
  check-db-schema-up-to-date:
    name: "check-db-schema-up-to-date"
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker-compose build
      - run: docker-compose --env-file=.env.test run web bundle exec rails db:create
      - run: docker-compose --env-file=.env.test run web bundle exec rails db:migrate
      - run: |
          [ -z "$(git status -s -- db/schema.rb)" ]
